version: '3.8'

services:
  mysql_db:
    image: mysql:8.0
    container_name: mysql_notif_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: notif_app_db
      MYSQL_USER: user_notif
      MYSQL_PASSWORD: pass123
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin_app:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_notif_app
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql_db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - mysql_db

volumes:
  mysql_data: